### ISSUE TITLE
How to generate the offline style fonts?

### ISSUE THREAD

**Issue by hmppt** [dailenson/SDT#7]
As stated in your paper, your work supports generating offline fonts, so how to generate offline fonts. 

By the way, qualitative testing is time consuming！

![image](https://github.com/dailenson/SDT/assets/43752397/d11e25b0-38ba-4561-a44f-78764165cfbc)

**Comment by dailenson** [comment]
Hi~ To access further details on offline handwriting generation, please refer to Appendix A.4 of our paper. Regarding the issue of time consumption, we kindly recommend that you utilize a GPU instead of a CPU to run our SDT for better time efficiency. This will result in a runtime of approximately 20 minutes on a single RTX3090 GPU when the sample size sets 500.
